### ISSUE TITLE
Зачет. Автомат?

### ISSUE THREAD

**Issue by MrRooots** [MrRooots/OSiTP2020#4]
Сергей Иванович, здравствуйте.
Если в графе "зачетная оценка" стоит удовлетворительно, то это значит, что зачет уже есть и завтра приходить не надо?

![image](https://user-images.githubusercontent.com/46628524/172856610-49a18d11-7e20-4476-9619-1a57da1052fb.png)

**Comment by justjune** [comment]
Никита, да это означает зачет.
